Set up associations between classes and objects.
milen-ale/school_library pull request #4
Opened 2022-11-03 18:25 UTC by milen-ale

In this PR I managed to do the following

- [ ] Set up associations between classes and objects.
  - Created a class `Classroom` with the following:
  - `@label` instance variable
  - Setter and getter for `@label`
- Created the `has-many`/`belongs-to` relationship between `Classroom` and `Student` and implemented the following
  - Created the `has-many` side (a classroom has many students).
  - Created the `belongs-to` side (a student belongs to a classroom).
- Created a class `Book` with the following:
  - `@title` and `@author` instance variables
  - Setters and getters for instance variables 
- Created a class `Rental` with the following:
  - `@date` instance variable
  - Setter and getter for `@date` 
- Created the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`. The following should be implemented:
  - Create the `has-many` side of `Book` and `Rental` (a book has many rentals).
  - Create the `belongs-to` side of `Rental` and `Book` (a rental belongs to a book).
  - Create the `has-many` side of `Person` and `Rental` (a person has many rentals).
  - Create the `belongs-to` side of `Rental` and `Person` (a rental belongs to a person).
  - Modified the constructor of `Rental` so `Book` and `Person` are set in it.

2022-11-03 21:02 UTC, victorokoroji requested changes
Hi @milen-ale, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] Good job so far 👍🏽 . Please add the relationships/ associations for the `Person `class (person.rb) as well

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 21:02 UTC, victorokoroji commented on School/book.rb
> +  attr_reader rental
- [ ] KIndly re-write the attr_accessor properly by adding a colon before the rental attribute 👍🏽 

e.g. `attr_reader :rental`

2022-11-03 21:02 UTC, victorokoroji commented on School/classroom.rb
> +  attr_accessor label
- [ ] KIndly re-write the attr_accessor properly by adding a colon before the label attribute 👍🏽 

e.g. `attr_reader :label`

2022-11-03 21:02 UTC, victorokoroji commented on School/classroom.rb
> +    @students = students[] # classroom has many students
- [ ] It is best you initialize the @students variable with just an empty array 👍🏽 

e.g `@students = []`

2022-11-03 21:02 UTC, victorokoroji commented on School/book.rb
> +    @rental = rental[]
- [ ] It is best you initialize the @rental variable with just an empty array 👍🏽

e.g @rental = []

2022-11-03 21:02 UTC, victorokoroji commented on School/book.rb
> +  def add_rental(rental)
- [ ] Kindly note that the book itself and the person should be sent as a parameter to create the new rental achieving the 'has-many' association. 
e.g.
  
```
 def add_rental(person, date)
    Rental.new(date, self, person)
  end
```

2022-11-04 08:59 UTC, t-yanick requested changes
Hi @milen-ale, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 08:59 UTC, t-yanick commented on School/book.rb
> +    @rentals.push(rental)
- [ ] As requested by the previous code reviewer,  book itself and the person should be sent as a parameter to create the new rental achieving the 'has-many' association. Your `add_rental` method is still missing person and book parameters. Please kindly fix that.

2022-11-04 08:59 UTC, t-yanick commented on School/classroom.rb
> +  attr_accessor label
- [ ] As requested by the previous code reviewer, please kindly correct the syntax error, re-write the attr_accessor properly by adding a `colon` before the label instance variable.

2022-11-04 09:57 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 10:57 UTC, merged