OOP school library: preserve data
milen-ale/school_library pull request #7
Opened 2022-11-09 14:53 UTC by t-bello7

- Check the documentation for Ruby's [JSON library](https://ruby-doc.org/stdlib-3.0.0/libdoc/json/rdoc/JSON.html).
- On exit from your app save all the data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. rentals.json)
- `On startup of your app load all data from files. Remember to handle the case when one or more of the files are missing.

2022-11-09 15:24 UTC, FrederickMih requested changes
Hi @t-bello7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/200513495-01ae8639-d7ee-4fbe-b6b0-927cf123a026.png)


## Highlights :green_circle: 


- Correct Gitflow has been followed :heavy_check_mark: 
- PR has a good title and summary :heavy_check_mark: 
- No Linter error :heavy_check_mark: 


## Required Changes ♻️

- [ ] Hi @team, this is a collaborative project. The Authors section of the README.md file should contain all members who contributed to this project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 15:24 UTC, FrederickMih commented on app.rb
>  end
- [ ] On exit from the app, I got this console error on the screenshot below:

![Screenshot from 2022-11-09 16-09-01](https://user-images.githubusercontent.com/63087491/200868017-97f4a041-d0a3-4027-97e2-9b4680006e9f.png)

- Based on the requirements of this project all the data registered(people, books, rentals) should be saved into JSON files. Kindly fix the issue.

2022-11-09 15:50 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @milen-ale, and @t-bello7👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] As requested by the previous reviewer, Please make sure the Authors section of the README file should contain all members who contributed to this project.

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 15:50 UTC, thecodechaser commented on main.rb
> +  load_rentals(@app)
- [ ] After creating rentals and exiting the app, When I run the app again I get get the below error. Please fix this issue and make sure that rentals are loaded successfully after starting the app.

![image](https://user-images.githubusercontent.com/83803414/200875823-135e4c73-ce55-4e11-ae31-bbe3b79ccc68.png)

2022-11-10 07:22 UTC, brytebee approved these changes
Hi Team👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-10 07:39 UTC, merged